---
engine_version: 0.4.36
file_version: 2025-04-08 15:28:27.317334000 Z
resources:
- name: assembly
  preferences:
    display_name: Samenstellingen
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
    - name: name
      display_name: name
      column_type: string
      access_type: read_only
      virtual: true
      format: {}
      validators: []
      description: Name
    - reference:
        name: parent
        display_name: Parent
        model_name: family
        reference_type: belongs_to
        foreign_key: parent_family_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      display_name: Product
      name: parent_family_id
    - reference:
        name: child
        display_name: Child
        model_name: family
        reference_type: belongs_to
        foreign_key: child_family_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      display_name: Ingredient
      name: child_family_id
    - access_type: hidden
      name: id
    - display_name: Gewicht
      name: weight
    - name: fraction
      display_name: fraction
      column_type: float
      access_type: read_only
      virtual: true
      format: {}
      validators: []
      description: Aandeel in het totale gewicht van de ingredienten
    - name: weight_base
      display_name: weight_base
      column_type: string
      access_type: read_only
      virtual: true
      format: {}
      validators: []
      description: Het gewicht in kg zoals verwerkt
    icon: abacus
  updated_at: 2025-03-20 08:04:42.457000000 +01:00
- name: bag
  preferences:
    icon: paper-bag
    columns:
    - access_type: hidden
      name: created_at
    custom_sql: SELECT `bags`.* FROM `bags` ORDER BY name
    display_name: Verpakkingen
  updated_at: 2025-03-17 22:47:58.063624000 +01:00
- name: batch
  preferences:
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: id
    display_column: batch_uid
    icon: asset
  updated_at: 2025-02-26 20:20:09.338044000 +01:00
- name: batch_input
  preferences:
    display_name: Batch Input
    columns:
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: updated_at
  updated_at: 2025-02-26 17:04:46.880230000 +01:00
- name: batch_output
  preferences:
    display_name: Batch Output
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
  updated_at: 2025-02-26 16:58:36.177588000 +01:00
- name: batch_packaging
  preferences:
    display_name: Batch Created
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: id
    icon: arrow-bottom-circle
  updated_at: 2025-02-26 20:22:54.083916000 +01:00
- name: batch_product
  preferences:
    display_name: Batch Used
    columns:
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: id
    icon: anchor
  updated_at: 2025-02-26 20:22:46.384746000 +01:00
- name: family
  preferences:
    associations:
    - display_name: Samenstelligen
      name: assemblies
    - display_name: Producten
      name: products
    icon: face-id
    columns:
    - name: total_assembly_weight_in_kg_f
      display_name: total_assembly_weight_in_kg_f
      column_type: string
      access_type: read_write
      virtual: true
      format: {}
      validators: []
      description: ''
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: updated_at
    - column_type: textarea
      name: components
    - column_type: textarea
      name: composition
  updated_at: 2025-03-28 14:55:44.339028000 +01:00
- name: label
  preferences:
    icon: tag
    custom_sql: SELECT `labels`.* FROM `labels` ORDER BY nicelabel_name
  updated_at: 2024-05-24 08:38:59.488478000 +02:00
- name: plant
  preferences:
    icon: building-factory-2
    display_name: Vestigingen
  updated_at: 2025-03-17 22:48:04.791700000 +01:00
- name: printed
  preferences:
    icon: printer
    columns:
    - access_type: hidden
      name: UpdatedAt
    - access_type: hidden
      name: CreatedAt
    - name: best_before_date_date
      display_name: BestBeforeDate_date
      column_type: date
      access_type: hidden
      virtual: true
      format: {}
      validators: []
      description: ''
    - reference:
        name: product
        display_name: Product
        model_name: product
        reference_type: belongs_to
        foreign_key: code
        primary_key: Itemcode
        options: {}
        polymorphic:
        virtual: false
      access_type: hidden
      name: code
    - access_type: hidden
      name: BestBeforeDate
    - access_type: hidden
      name: NicelabelId
    scopes:
    - name: not_imported_into_eo
      display_name: Not imported into EO
      scope_type: filter
      preferences:
        filter:
        - XMLExported:
            neq: true
        sort:
          key: id
          order: desc
    - visible: false
      name: xml_exported_at_not_nil
    - visible: false
      name: xml_exported_at_nil
    display_name: Etiketten
  updated_at: 2025-03-17 22:48:15.313957000 +01:00
- name: product
  preferences:
    icon: box
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
    - name: name
      display_name: Name
      column_type: string
      access_type: hidden
      virtual: true
      format: {}
      validators: []
      description: Name
    - name: weight_in_kg
      display_name: weight_in_kg
      column_type: string
      access_type: hidden
      virtual: true
      format: {}
      validators: []
      description: ''
    - access_type: hidden
      reference:
        name: plant
        display_name: Plant
        model_name: plant
        reference_type: belongs_to
        foreign_key: plant_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      name: plant_id
    - reference:
        name: family
        display_name: Family
        model_name: family
        reference_type: belongs_to
        foreign_key: family_id
        primary_key: id
        options: {}
        polymorphic:
        virtual: false
      name: family_id
    - access_type: hidden
      name: id
    - access_type: hidden
      name: print_label_repack
    - access_type: hidden
      name: label_background_url
    - default_value:
      name: is_input
    display_column: name
    display_name: Producten
  updated_at: 2025-03-28 15:00:39.006500000 +01:00
- name: production/batch
  preferences:
    display_name: 'P: Batches'
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
  updated_at: 2025-02-25 16:32:20.494617000 +01:00
- name: production/batch_ingredient
  preferences:
    columns:
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: updated_at
    display_name: 'P: Batch Ingredients'
  updated_at: 2025-02-25 16:17:47.723610000 +01:00
- name: production/batch_output
  preferences:
    display_name: 'P: Batch Packagings'
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
  updated_at: 2025-02-25 16:19:07.121216000 +01:00
- name: production/batch_packaging
  preferences:
    display_name: 'P: Batch Packagings'
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
  updated_at: 2025-02-25 16:19:07.121216000 +01:00
- name: production/packaging
  preferences:
    display_name: 'P: Packagings'
  updated_at: 2025-02-25 16:31:26.388194000 +01:00
- name: production/product
  preferences:
    columns:
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: updated_at
    display_name: 'P: Products'
  updated_at: 2025-02-25 16:18:27.612745000 +01:00
- name: production/product_ingredient
  preferences:
    display_name: 'P: Product Ingredients'
    columns:
    - access_type: hidden
      name: updated_at
    - access_type: hidden
      name: created_at
    - access_type: hidden
      name: id
  updated_at: 2025-02-25 16:21:10.238754000 +01:00
- name: production/product_packaging
  preferences:
    display_name: 'P: Product Packagings'
    associations:
    - name: packaging
      display_name: packaging
      model_name: production/packaging
      foreign_key: id
      primary_key: packaging_id
      virtual: true
      polymorphic: false
      slug: packaging
  updated_at: 2025-02-25 16:24:03.338085000 +01:00
configs:
- key: header.links
  value:
  - conditions: []
    type: header
    name: Home
    path: https://repacman.bio-ron.com
    link_type: header
  - name: Reports
    link_type: reports
  - name: Forms
    link_type: forms
  - conditions: []
    type: header
    name: Google
    path: https://www.google.com/
    link_type: header
  - conditions: []
    type: header
    name: Bio-Ron
    path: https://repacman.bio-ron.com
    link_type: header
  updated_at: 2025-03-20 08:13:01.128529000 +01:00
- key: resources.assembly.columns.order
  value:
  - id
  - parent_family_id
  - child_family_id
  - name
  - weight
  - updated_at
  - created_at
  - fraction
  - weight_base
  updated_at: 2025-03-20 08:04:42.817694000 +01:00
- key: resources.batch.associations.order
  value:
  - batch_products
  - batch_packagings
  updated_at: 2025-02-26 20:47:52.416012000 +01:00
- key: resources.family.columns.order
  value:
  - id
  - name
  - composition
  - components
  - additives
  - dosage
  - claims
  - instructions
  - tht_months
  - manufacturer_code
  - bio
  - is_batch
  - updated_at
  - created_at
  - total_assembly_weight_in_kg_scalar
  updated_at: 2025-03-17 07:52:01.302933000 +01:00
- key: resources.order
  value:
  - family
  - assembly
  - product
  - bag
  - plant
  - label
  - printed
  - batch
  - batch_output
  - batch_input
  updated_at: 2025-03-17 09:23:23.391049000 +01:00
- key: resources.plant.columns.order
  value:
  - id
  - name
  - streetnr
  - zip
  - city
  - country
  - updated_at
  - created_at
  updated_at: 2024-05-30 09:45:20.434262000 +02:00
- key: resources.printed.columns.order
  value:
  - id
  - XMLExported
  - code
  - NicelabelId
  - RepackDate
  - ItemCode
  - WarehouseCode
  - PlannedQuantity
  - ProductDescription
  - Weight
  - Batch
  - MotherBatch
  - Best_Before_Date
  - BestBeforeDate
  - CreatedAt
  - UpdatedAt
  - xml_exported_at
  - best_before_date_date
  updated_at: 2025-01-06 11:16:30.782709000 +01:00
- key: resources.product.columns.order
  value:
  - id
  - code
  - family_id
  - weight
  - barcode
  - bag_id
  - label_id
  - plant_id
  - updated_at
  - created_at
  updated_at: 2024-05-23 19:49:31.610989000 +02:00
queries:
- id: 1
  name: Nicelabel INPUT
  sql_body: SELECT * FROM nicelabel_input
  description: The input as presented to Nicelabel
  preferences:
    query_type: sql
    database: primary
    visualization: table
    visualization_options: {}
    variables: []
  tags: []
  updated_at: 2024-05-23 13:26:09.580257000 +02:00
- id: 2
  name: Summary
  sql_body: SELECT * FROM summary
  description:
  preferences:
    query_type: sql
    database: primary
    visualization: table
    visualization_options: {}
    variables: []
  tags: []
  updated_at: 2024-05-23 13:27:20.744803000 +02:00
- id: 3
  name: Production Labels To Print
  sql_body: SELECT * FROM production_labels WHERE output_label_printed_at IS NULL;
  description: SELECT * FROM production_labels WHERE output_label_printed_at IS NULL;
  preferences:
    query_type: sql
    database: primary
    visualization: table
    visualization_options: {}
    variables: []
  tags: []
  updated_at: 2025-04-08 17:28:27.317334000 +02:00
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2024-05-23 12:36:20.714190000 +02:00
